//! Wavefront OBJ conversion through the OMF data model.

use std::{collections::HashMap, io::Write};

use crate::{
    Attribute, AttributeData, Element, Geometry, LineSet, Location, PointSet, Project, Surface,
    format::{
        ByteStreams, all_elements,
        omf::{Document, MemoryWriter},
    },
};

const NORMAL: &str = "obj:normal";
const TEXCOORD: &str = "obj:texcoord";
const COLOR: &str = "obj:color";

/// An OBJ conversion failure.
#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("could not serialize OBJ bytes: {0}")]
    Io(#[from] std::io::Error),
    #[error("OBJ bytes are not valid UTF-8: {0}")]
    Utf8(#[from] std::str::Utf8Error),
    #[error("could not read or write OMF: {0}")]
    Omf(#[from] ::omf::error::Error),
    #[error("invalid or unsupported OBJ at line {line}: {reason}")]
    Parse { line: usize, reason: String },
    #[error("OBJ material data is not representable by this adapter (line {0})")]
    Material(usize),
    #[error("the OMF document contains no geometry that OBJ can serialize")]
    NothingToSerialize,
    #[error("OMF attribute {attribute:?} on element {element:?} is invalid for OBJ: {reason}")]
    Attribute { element: String, attribute: String, reason: String },
    #[error("OBJ object {0:?} contains no point, line, or polygon primitives")]
    EmptyObject(String),
    #[error("OBJ geometry is inconsistent: {0}")]
    Inconsistent(String),
}

/// Deserialize OBJ bytes into the shared in-memory OMF representation.
pub fn deserialize(bytes: &[u8]) -> Result<Document, Error> {
    let source = std::str::from_utf8(bytes)?;
    Document::build(|writer| read_project(source, writer))
}

fn read_project(source: &str, writer: &mut MemoryWriter) -> Result<Project, Error> {
    let mut data = parse(source)?;
    let mut project = Project::new("OBJ project");
    project.application = format!("mfsd {}", env!("CARGO_PKG_VERSION"));

    let objects = std::mem::take(&mut data.objects);
    for object in objects {
        let part_count = usize::from(!object.points.is_empty()) + usize::from(!object.lines.is_empty()) + usize::from(!object.faces.is_empty());
        if part_count == 0 {
            continue;
        }

        if !object.points.is_empty() {
            let refs = object.points;
            let mut element = Element::new(
                part_name(&object.name, "points", part_count),
                PointSet::new(writer.array_vertices(select_vertices(&data, &refs))?),
            );
            element.attributes = vertex_attributes(writer, &data, &refs)?;
            project.elements.push(element);
        }

        if !object.lines.is_empty() {
            let (refs, segments) = remap_primitives(&object.lines);
            let mut element = Element::new(
                part_name(&object.name, "lines", part_count),
                LineSet::new(writer.array_vertices(select_vertices(&data, &refs))?, writer.array_segments(segments)?),
            );
            element.attributes = vertex_attributes(writer, &data, &refs)?;
            project.elements.push(element);
        }

        if !object.faces.is_empty() {
            let (refs, triangles) = remap_primitives(&object.faces);
            let mut element = Element::new(
                part_name(&object.name, "surface", part_count),
                Surface::new(writer.array_vertices(select_vertices(&data, &refs))?, writer.array_triangles(triangles)?),
            );
            element.attributes = vertex_attributes(writer, &data, &refs)?;
            project.elements.push(element);
        }
    }
    if project.elements.is_empty() {
        return Err(Error::EmptyObject("OBJ file".to_owned()));
    }
    Ok(project)
}

/// Serialize every OBJ-compatible OMF element into one OBJ byte stream.
///
/// OBJ natively contains multiple named objects, so all compatible elements
/// share one output stream. Unsupported elements and attributes are omitted.
/// An error is returned when there is no compatible geometry to serialize.
pub fn serialize(document: &Document) -> Result<ByteStreams, Error> {
    let mut out = Vec::new();
    writeln!(out, "# Generated by mfsd {}", env!("CARGO_PKG_VERSION"))?;
    let mut offsets = ObjOffsets::default();
    let mut serialized = false;

    for element in all_elements(&document.project().elements) {
        match &element.geometry {
            Geometry::PointSet(points) => {
                serialized = true;
                writeln!(out, "o {}", obj_name(&element.name))?;
                let vertices = read_vertices(document, &points.vertices, points.origin)?;
                let attributes = read_obj_attributes(document, element, vertices.len(), false, false)?;
                write_vertices(&mut out, &vertices, &attributes)?;
                for i in 0..vertices.len() {
                    writeln!(out, "p {}", offsets.vertices + i as u64)?;
                }
                offsets.advance(vertices.len(), &attributes);
            }
            Geometry::LineSet(lines) => {
                serialized = true;
                writeln!(out, "o {}", obj_name(&element.name))?;
                let vertices = read_vertices(document, &lines.vertices, lines.origin)?;
                let attributes = read_obj_attributes(document, element, vertices.len(), false, true)?;
                write_vertices(&mut out, &vertices, &attributes)?;
                for segment in document.reader().array_segments(&lines.segments)? {
                    let [a, b] = segment?;
                    write!(out, "l")?;
                    write_line_index(&mut out, offsets, u64::from(a), &attributes)?;
                    write_line_index(&mut out, offsets, u64::from(b), &attributes)?;
                    writeln!(out)?;
                }
                offsets.advance(vertices.len(), &attributes);
            }
            Geometry::Surface(surface) => {
                serialized = true;
                writeln!(out, "o {}", obj_name(&element.name))?;
                let vertices = read_vertices(document, &surface.vertices, surface.origin)?;
                let attributes = read_obj_attributes(document, element, vertices.len(), true, true)?;
                write_vertices(&mut out, &vertices, &attributes)?;
                for triangle in document.reader().array_triangles(&surface.triangles)? {
                    let [a, b, c] = triangle?;
                    write!(out, "f")?;
                    for index in [a, b, c] {
                        write_face_index(&mut out, offsets, u64::from(index), &attributes)?;
                    }
                    writeln!(out)?;
                }
                offsets.advance(vertices.len(), &attributes);
            }
            _ => {}
        }
    }
    if !serialized {
        return Err(Error::NothingToSerialize);
    }
    out.flush()?;
    Ok(vec![out])
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
struct VertexRef {
    vertex: usize,
    texcoord: Option<usize>,
    normal: Option<usize>,
}

#[derive(Default)]
struct ObjData {
    positions: Vec<[f64; 3]>,
    colors: Vec<Option<[f64; 3]>>,
    texcoords: Vec<[f64; 3]>,
    normals: Vec<[f64; 3]>,
    objects: Vec<Object>,
}

#[derive(Default)]
struct Object {
    name: String,
    points: Vec<VertexRef>,
    lines: Vec<[VertexRef; 2]>,
    faces: Vec<[VertexRef; 3]>,
}

impl Object {
    fn has_primitives(&self) -> bool {
        !self.points.is_empty() || !self.lines.is_empty() || !self.faces.is_empty()
    }
}

fn parse(source: &str) -> Result<ObjData, Error> {
    let mut data = ObjData::default();
    let mut object = Object {
        name: "unnamed_object".to_owned(),
        ..Default::default()
    };

    for (index, raw_line) in source.lines().enumerate() {
        let line_number = index + 1;
        let line = raw_line.split('#').next().unwrap_or_default().trim();
        if line.is_empty() {
            continue;
        }
        let mut words = line.split_whitespace();
        let command = words.next().unwrap_or_default();
        match command {
            "v" => {
                let values = parse_floats(words, line_number, "vertex")?;
                let (position, color) = match values.as_slice() {
                    [x, y, z] => ([*x, *y, *z], None),
                    [x, y, z, w] if *w != 0.0 => ([*x / *w, *y / *w, *z / *w], None),
                    [x, y, z, r, g, b] => ([*x, *y, *z], Some([*r, *g, *b])),
                    _ => {
                        return Err(parse_error(line_number, "vertex must have x y z, optional w, or optional r g b"));
                    }
                };
                data.positions.push(position);
                data.colors.push(color);
            }
            "vt" => {
                let values = parse_floats(words, line_number, "texture coordinate")?;
                let value = match values.as_slice() {
                    [u] => [*u, 0.0, 0.0],
                    [u, v] => [*u, *v, 0.0],
                    [u, v, w] => [*u, *v, *w],
                    _ => {
                        return Err(parse_error(line_number, "texture coordinate must have one to three values"));
                    }
                };
                data.texcoords.push(value);
            }
            "vn" => {
                let values = parse_floats(words, line_number, "normal")?;
                let [x, y, z] = <[f64; 3]>::try_from(values).map_err(|_| parse_error(line_number, "normal must have three values"))?;
                data.normals.push([x, y, z]);
            }
            "p" => {
                let refs = parse_refs(words, &data, line_number)?;
                if refs.is_empty() {
                    return Err(parse_error(line_number, "point statement is empty"));
                }
                object.points.extend(refs);
            }
            "l" => {
                let refs = parse_refs(words, &data, line_number)?;
                if refs.len() < 2 {
                    return Err(parse_error(line_number, "line must have at least two vertices"));
                }
                object.lines.extend(refs.windows(2).map(|pair| [pair[0], pair[1]]));
            }
            "f" => {
                let refs = parse_refs(words, &data, line_number)?;
                let triangle = <[VertexRef; 3]>::try_from(refs).map_err(|_| parse_error(line_number, "OMF surfaces require triangular faces; triangulate this OBJ first"))?;
                object.faces.push(triangle);
            }
            "o" | "g" => {
                let name = line[command.len()..].trim();
                if name.is_empty() {
                    return Err(parse_error(line_number, "object/group name is empty"));
                }
                if object.has_primitives() {
                    data.objects.push(object);
                    object = Object::default();
                }
                object.name = name.to_owned();
            }
            "mtllib" | "usemtl" => return Err(Error::Material(line_number)),
            "vp" => {
                return Err(parse_error(line_number, "free-form parameter vertices have no OMF geometry equivalent"));
            }
            "s" => {}
            _ => {
                return Err(parse_error(line_number, format!("unsupported OBJ statement {command:?}")));
            }
        }
    }
    if object.has_primitives() {
        data.objects.push(object);
    }
    Ok(data)
}

fn parse_floats<'a>(values: impl Iterator<Item = &'a str>, line: usize, field: &str) -> Result<Vec<f64>, Error> {
    values
        .map(|value| {
            value
                .parse::<f64>()
                .map_err(|_| parse_error(line, format!("invalid {field} value {value:?}")))
                .and_then(|value| value.is_finite().then_some(value).ok_or_else(|| parse_error(line, format!("non-finite {field} value"))))
        })
        .collect()
}

fn parse_refs<'a>(values: impl Iterator<Item = &'a str>, data: &ObjData, line: usize) -> Result<Vec<VertexRef>, Error> {
    values
        .map(|value| {
            let parts = value.split('/').collect::<Vec<_>>();
            if parts.is_empty() || parts.len() > 3 || parts[0].is_empty() {
                return Err(parse_error(line, format!("invalid vertex reference {value:?}")));
            }
            Ok(VertexRef {
                vertex: parse_index(parts[0], data.positions.len(), line, "vertex")?,
                texcoord: parts
                    .get(1)
                    .filter(|part| !part.is_empty())
                    .map(|part| parse_index(part, data.texcoords.len(), line, "texture coordinate"))
                    .transpose()?,
                normal: parts
                    .get(2)
                    .filter(|part| !part.is_empty())
                    .map(|part| parse_index(part, data.normals.len(), line, "normal"))
                    .transpose()?,
            })
        })
        .collect()
}

fn parse_index(value: &str, len: usize, line: usize, field: &str) -> Result<usize, Error> {
    let index = value.parse::<isize>().map_err(|_| parse_error(line, format!("invalid {field} index {value:?}")))?;
    let resolved = if index > 0 {
        index - 1
    } else if index < 0 {
        len as isize + index
    } else {
        return Err(parse_error(line, format!("{field} index zero is invalid")));
    };
    if resolved < 0 || resolved as usize >= len {
        return Err(parse_error(line, format!("{field} index {value} is out of bounds")));
    }
    Ok(resolved as usize)
}

fn remap_primitives<const N: usize>(primitives: &[[VertexRef; N]]) -> (Vec<VertexRef>, Vec<[u32; N]>) {
    let mut refs = Vec::new();
    let mut remap = HashMap::new();
    let output = primitives
        .iter()
        .map(|primitive| {
            primitive.map(|reference| {
                *remap.entry(reference).or_insert_with(|| {
                    let index = refs.len() as u32;
                    refs.push(reference);
                    index
                })
            })
        })
        .collect();
    (refs, output)
}

fn select_vertices(data: &ObjData, refs: &[VertexRef]) -> Vec<[f64; 3]> {
    refs.iter().map(|reference| data.positions[reference.vertex]).collect()
}

fn vertex_attributes(writer: &mut MemoryWriter, data: &ObjData, refs: &[VertexRef]) -> Result<Vec<Attribute>, Error> {
    let mut attributes = Vec::new();
    let normal_count = refs.iter().filter(|reference| reference.normal.is_some()).count();
    if normal_count != 0 {
        if normal_count != refs.len() {
            return Err(Error::Inconsistent("a geometry mixes vertices with and without normals".to_owned()));
        }
        let values = refs.iter().map(|reference| Some(data.normals[reference.normal.unwrap()]));
        attributes.push(Attribute::from_vectors(NORMAL, Location::Vertices, writer.array_vectors(values)?));
    }

    let texcoord_count = refs.iter().filter(|reference| reference.texcoord.is_some()).count();
    if texcoord_count != 0 {
        if texcoord_count != refs.len() {
            return Err(Error::Inconsistent("a geometry mixes vertices with and without texture coordinates".to_owned()));
        }
        let values = refs.iter().map(|reference| Some(data.texcoords[reference.texcoord.unwrap()]));
        attributes.push(Attribute::from_vectors(TEXCOORD, Location::Vertices, writer.array_vectors(values)?));
    }

    let color_count = refs.iter().filter(|reference| data.colors[reference.vertex].is_some()).count();
    if color_count != 0 {
        if color_count != refs.len() {
            return Err(Error::Inconsistent("a geometry mixes vertices with and without colors".to_owned()));
        }
        let values = refs.iter().map(|reference| data.colors[reference.vertex]);
        attributes.push(Attribute::from_vectors(COLOR, Location::Vertices, writer.array_vectors(values)?));
    }
    Ok(attributes)
}

#[derive(Default)]
struct ObjAttributes {
    normals: Option<Vec<[f64; 3]>>,
    texcoords: Option<Vec<[f64; 3]>>,
    colors: Option<Vec<[f64; 3]>>,
}

fn read_obj_attributes(document: &Document, element: &Element, vertex_count: usize, allow_normals: bool, allow_texcoords: bool) -> Result<ObjAttributes, Error> {
    let mut output = ObjAttributes::default();
    for attribute in &element.attributes {
        let supported = match attribute.name.as_str() {
            NORMAL => allow_normals && output.normals.is_none(),
            TEXCOORD => allow_texcoords && output.texcoords.is_none(),
            COLOR => output.colors.is_none(),
            _ => false,
        };
        if !supported {
            continue;
        }
        if attribute.location != Location::Vertices {
            continue;
        }
        let AttributeData::Vector { values } = &attribute.data else {
            continue;
        };
        let values = document
            .reader()
            .array_vectors(values)?
            .map(|value| value?.ok_or_else(|| attribute_error(element, attribute, "null values are not supported")))
            .collect::<Result<Vec<_>, Error>>()?;
        if values.len() != vertex_count {
            return Err(attribute_error(element, attribute, "length does not match the vertex count"));
        }
        match attribute.name.as_str() {
            NORMAL => output.normals = Some(values),
            TEXCOORD => output.texcoords = Some(values),
            COLOR => output.colors = Some(values),
            _ => unreachable!("unsupported attributes were filtered above"),
        }
    }
    Ok(output)
}

fn write_vertices(out: &mut impl Write, vertices: &[[f64; 3]], attributes: &ObjAttributes) -> Result<(), Error> {
    for (i, [x, y, z]) in vertices.iter().copied().enumerate() {
        if let Some(colors) = &attributes.colors {
            let [r, g, b] = colors[i];
            writeln!(out, "v {x} {y} {z} {r} {g} {b}")?;
        } else {
            writeln!(out, "v {x} {y} {z}")?;
        }
    }
    if let Some(texcoords) = &attributes.texcoords {
        for [u, v, w] in texcoords {
            if *w == 0.0 {
                writeln!(out, "vt {u} {v}")?;
            } else {
                writeln!(out, "vt {u} {v} {w}")?;
            }
        }
    }
    if let Some(normals) = &attributes.normals {
        for [x, y, z] in normals {
            writeln!(out, "vn {x} {y} {z}")?;
        }
    }
    Ok(())
}

#[derive(Clone, Copy)]
struct ObjOffsets {
    vertices: u64,
    texcoords: u64,
    normals: u64,
}

impl Default for ObjOffsets {
    fn default() -> Self {
        Self {
            vertices: 1,
            texcoords: 1,
            normals: 1,
        }
    }
}

impl ObjOffsets {
    fn advance(&mut self, count: usize, attributes: &ObjAttributes) {
        self.vertices += count as u64;
        if attributes.texcoords.is_some() {
            self.texcoords += count as u64;
        }
        if attributes.normals.is_some() {
            self.normals += count as u64;
        }
    }
}

fn write_face_index(out: &mut impl Write, offsets: ObjOffsets, local: u64, attributes: &ObjAttributes) -> Result<(), Error> {
    let vertex = offsets.vertices + local;
    let texcoord = offsets.texcoords + local;
    let normal = offsets.normals + local;
    match (attributes.texcoords.is_some(), attributes.normals.is_some()) {
        (false, false) => write!(out, " {vertex}")?,
        (true, false) => write!(out, " {vertex}/{texcoord}")?,
        (false, true) => write!(out, " {vertex}//{normal}")?,
        (true, true) => write!(out, " {vertex}/{texcoord}/{normal}")?,
    }
    Ok(())
}

fn write_line_index(out: &mut impl Write, offsets: ObjOffsets, local: u64, attributes: &ObjAttributes) -> Result<(), Error> {
    let vertex = offsets.vertices + local;
    if attributes.texcoords.is_some() {
        write!(out, " {vertex}/{}", offsets.texcoords + local)?;
    } else {
        write!(out, " {vertex}")?;
    }
    Ok(())
}

fn read_vertices(document: &Document, array: &::omf::Array<::omf::array_type::Vertex>, geometry_origin: [f64; 3]) -> Result<Vec<[f64; 3]>, Error> {
    let project_origin = document.project().origin;
    document
        .reader()
        .array_vertices(array)?
        .map(|vertex| {
            let vertex = vertex?;
            Ok([
                vertex[0] + geometry_origin[0] + project_origin[0],
                vertex[1] + geometry_origin[1] + project_origin[1],
                vertex[2] + geometry_origin[2] + project_origin[2],
            ])
        })
        .collect()
}

fn parse_error(line: usize, reason: impl Into<String>) -> Error {
    Error::Parse { line, reason: reason.into() }
}

fn attribute_error(element: &Element, attribute: &Attribute, reason: impl Into<String>) -> Error {
    Error::Attribute {
        element: element.name.clone(),
        attribute: attribute.name.clone(),
        reason: reason.into(),
    }
}

fn part_name(object: &str, part: &str, part_count: usize) -> String {
    let object = if object.is_empty() { "OBJ object" } else { object };
    if part_count == 1 { object.to_owned() } else { format!("{object} ({part})") }
}

fn obj_name(name: &str) -> String {
    name.chars().map(|character| if character.is_whitespace() { '_' } else { character }).collect()
}
